src/main/java/com/arms/analysis/time/controller/일정분석_컨트롤러.java
src/main/java/com/arms/util/external_communicate/통계엔진통신기.java

- 오늘기준 1주일간 데이터 조회 API 생성
- 엔진 제품서비스_버전목록으로_주간조회 연결 #close #time 1h +review SR @313devops
클러스터2 : [DockerSwarm] …

:alien: feat: [Backend] #comment Time 분석을 위한 API 추가 - 23.12.09

---

src/main/java/com/arms/analysis/time/controller/일정분석_컨트롤러.java
src/main/java/com/arms/util/external_communicate/통계엔진통신기.java

- 엔진 검색 결과 버전별 그룹화 #close #time 1h +review SR @313devops
클러스터2 : [DockerSwarm] http://www.313.co.kr/portainer/#!/auth
디비 관리 …

:alien: refactor: [Backend] #comment Time 분석을 위한 주간 조회 API 수정 - 23.12.09

---

src/main/java/com/arms/analysis/time/controller/일정분석_컨트롤러.java
src/main/java/com/arms/util/external_communicate/통계엔진통신기.java

- 제품서비스_버전목록으로_주간_업데이트된_이슈조회로 변경
- 변경사유 : created 기준 조회에서 updated 기준 조회로 변경하였음 #close #time 1h +review SR @313devops
클러스터2 …

:alien: refactor: [Backend] #comment Time 분석을 위한 주간 조회 API 변경 - 23.12.10

---

src/main/java/com/arms/dashboard/controller/DashboardController.java
src/main/java/com/arms/dashboard/service/DashboardService.java
src/main/java/com/arms/dashboard/service/DashboardServiceImpl.java

- Dashboard 일부 미사용 ENDPOINT 제거
- 비즈니스로직은 Service Layer 로 이전
- 컨트롤러 return type 통일
#close #time 1h +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-254 more details.
[DB Admin] …

feat: [ARMS-254] #comment Dashboard 코드 정리 - 23.12.16

---

src/main/java/com/arms/analysis/time/controller/일정분석_컨트롤러.java
src/main/java/com/arms/util/external_communicate/통계엔진통신기.java

[ Backend-Core::Java-Service-Tree-Framework(JSTF)::chanho470 ] [Requirement Manage] http://www.a-rms.net
[MEM Admin] http://www.313.co.kr/redis/
[NoSql Index] …

:alien: feat: [Backend] #comment 업데이트된 이슈 일자 범위 검색 API 추가 - 23.12.18

---

src/main/java/com/arms/analysis/scope/controller/스코프분석_컨트롤러.java
src/main/java/com/arms/analysis/scope/dto/TreeBarDTO.java
src/main/java/com/arms/analysis/scope/service/ScopeService.java
src/main/java/com/arms/analysis/scope/service/ScopeServiceImpl.java

#close #time 3d +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-256 more details.
[MEM Admin] …

feat: [ARMS-256] #comment 트리바 Top 10 차트 - 23.12.21

---

src/main/java/com/arms/analysis/scope/service/ScopeServiceImpl.java

#close #time 1m +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-257 more details.
[MEM Admin] …

feat: [ARMS-257] #comment 트리바 Top 10 차트 - 23.12.21

---

src/main/java/com/arms/analysis/scope/service/ScopeServiceImpl.java

담당자 name 에 담당 중인 Sub-Task 개수 노출되도록 수정
#close #time 10m +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-263 more details.
[S3 Admin] …

feat: [ARMS-263] #comment 트리바 차트 UI 개선 - 23.12.22

---

src/main/java/com/arms/analysis/scope/service/ScopeServiceImpl.java

담당자 차트 기본 색상 원복
#close #time 10m +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-264 more details. …

feat: [ARMS-264] #comment 트리바 차트 API 수정 - 23.12.22

---

src/main/java/com/arms/dashboard/controller/DashboardController.java
src/main/java/com/arms/dashboard/model/TaskList.java
src/main/java/com/arms/dashboard/model/Worker.java
src/main/java/com/arms/dashboard/service/DashboardService.java
src/main/java/com/arms/dashboard/service/DashboardServiceImpl.java
src/main/java/com/arms/util/external_communicate/통계엔진통신기.java

#close #time 3h +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-266 more details.
[MEM Admin] …

feat: [ARMS-266] #comment  트리맵 차트 Echarts -> Jit 변경  - 23.12.23

---

src/main/java/com/arms/dashboard/model/SankeyData.java
src/main/java/com/arms/dashboard/service/DashboardServiceImpl.java

#close #time 30m +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-274 more details.
[MEM Admin] …

feat: [ARMS-274] #comment Sankey 가짜 작업자 노드 로직 수정 - 23.12.30

---

build.gradle
src/main/java/com/arms/api/slack/config/SlackConfig.java
src/main/java/com/arms/api/slack/config/SlackProperty.java
src/main/java/com/arms/api/slack/dto/SlackMessageDTO.java
src/main/java/com/arms/api/slack/service/SlackApiService.java
src/main/java/com/arms/api/slack/service/SlackResponse.java
src/main/java/com/arms/api/slack/service/SlackService.java
src/main/resources/application.yml

#close #time 30m +review SR @dumbbelloper
See https://dumbbelloper.atlassian.net/browse/DEMO-38 more details.
[MEM …

feat: [DEMO-38] #comment 알림 샘플 - 24.01.23

---

src/main/java/com/arms/api/analysis/time/controller/일정분석_컨트롤러.java
src/main/java/com/arms/api/analysis/time/service/TimeService.java
src/main/java/com/arms/api/analysis/time/service/TimeServiceImpl.java
src/main/java/com/arms/api/jira/jiraserver/service/JiraServerImpl.java
src/main/java/com/arms/api/util/external_communicate/통계엔진통신기.java

[ Backend-Core::Java-Service-Tree-Framework(JSTF)::Advanc2d ] [Requirement Manage] http://www.a-rms.net
[MEM Admin] http://www.313.co.kr/redis/
[NoSql Index] …

:see_no_evil: refactor: [Backend] #comment 일정 분석 컨트롤러 - 서비스 - 구현체 구조로 리팩토링 - 24.01.28

---

src/main/java/com/arms/api/jira/jiraserver/service/JiraServerImpl.java

🙈 feat: [PHM-125] #comment - 항목별 갱신 시 서버 유형  방어 코드 추가 - 24.03.28

---

src/main/java/com/arms/api/salary/controller/SalaryController.java
src/main/java/com/arms/api/salary/service/SalaryService.java
src/main/java/com/arms/api/salary/service/SalaryServiceImpl.java

#close #time 1m +review SR @dumbbelloper
[MEM Admin] http://www.313.co.kr/redis/
[NoSql Index] …

⚡️feat: [DEMO-134] #comment 연봉 업데이트 API 개선 - 24.03.30

---

src/main/java/com/arms/api/salary/controller/SalaryController.java
src/main/java/com/arms/api/salary/controller/SalaryLogController.java
src/main/java/com/arms/api/salary/model/SalaryLogDTO.java
src/main/java/com/arms/api/salary/model/SalaryLogEntity.java
src/main/java/com/arms/api/salary/service/SalaryLog.java
src/main/java/com/arms/api/salary/service/SalaryLogImpl.java
src/main/java/com/arms/api/salary/service/SalaryService.java
src/main/java/com/arms/api/salary/service/SalaryServiceImpl.java
src/main/resources/com/arms/db/V6__init_aRMS.sql

- flyway 연봉 LOG DB 추가
- SalaryLog ENDPOINT 추가
- 연봉 업데이트 API 인자 변경 및 개선
#close #time 1m +review SR @dumbbelloper
[ Backend-Core::Java-Service-Tree-Framework(JSTF)::313DEVGRP]
[Requirement Manage] http://www.a-rms.net
[MEM …

⚡️feat: [DEMO-136] #comment 연봉 LOG 추가 및 개선 - 24.03.31

---

src/main/java/com/arms/api/jira/jiraserver/controller/JiraServerController.java
src/main/java/com/arms/api/jira/jiraserver/model/계정정보_데이터.java
src/main/java/com/arms/api/util/communicate/external/엔진통신기.java

클러스터2 : [DockerSwarm] http://www.313.co.kr/portainer/#!/auth
디비 관리 : [DB Admin] …

:alien: feat: [RedMine#20] #comment 계정 검증 API 추가 - 24.04.01

---

src/main/java/com/arms/api/analysis/cost/controller/비용분석_컨트롤러.java
src/main/java/com/arms/api/analysis/cost/service/비용서비스.java
src/main/java/com/arms/api/analysis/cost/service/비용서비스_구현.java
src/main/java/com/arms/api/salary/model/SalaryLogEntity.java

#close #time 1m +review SR @dumbbelloper
[MEM Admin] http://www.313.co.kr/redis/
[NoSql Index] …

⚡️feat: [DEMO-140] #comment 제품 비용 차트 중간 커밋 - 24.04.01

---

src/main/java/com/arms/api/jira/jiraproject/controller/JiraProjectController.java
src/main/java/com/arms/api/jira/jiraproject/service/JiraProject.java
src/main/java/com/arms/api/jira/jiraproject/service/JiraProjectImpl.java
src/main/java/com/arms/api/jira/jiraserver/controller/JiraServerController.java
src/main/java/com/arms/api/jira/jiraserver/model/enums/EntityType.java
src/main/java/com/arms/api/jira/jiraserver/service/JiraServer.java
src/main/java/com/arms/api/jira/jiraserver/service/JiraServerImpl.java
src/main/java/com/arms/api/util/communicate/external/response/jira/ALM_데이터.java
src/main/java/com/arms/api/util/communicate/external/response/jira/지라이슈상태_데이터.java
src/main/java/com/arms/api/util/communicate/external/response/jira/지라이슈우선순위_데이터.java
src/main/java/com/arms/api/util/communicate/external/response/jira/지라이슈유형_데이터.java
src/main/java/com/arms/api/util/communicate/external/response/jira/지라이슈해결책_데이터.java
src/main/java/com/arms/api/util/communicate/external/response/jira/지라프로젝트_데이터.java

1. EntityType enum 추가
2. ALM_데이터 클래스 추가 -> 프로젝트, 이슈유형, 이슈상태, 이슈우선순위, 이슈해결책 5가지 엔티티 타입 중 공통 사용 부분 추상화 클래스로 적용 후 extends 하도록 변경하여 제네릭에서 사용할 수 있도록 처리
3. 서버_엔티티_동기화 메소드 유형 별 같은 형태의 로직 처리를 제네릭 사용하여 처리하도록 반영(리팩토링 필요하다 판단)
4. 엔티티 유형별 저장_또는_업데이트 로직 수행
5. 4번에서 업데이트 처리 시 완료 후 남은 데이터를 ALM 서버에서 삭제된 데이터로 판단하고 소프트 딜리트 처리
6. 소프트 딜리트 처리 시 check된 값인 경우 "false" 값으로 변경 처리
7. addJiraServer 메소드 -> 서버_엔티티_항목별_갱신 로직을 서버 생성 로직과 갱신 로직을 함께 사용하도록 처리 …

🙈 feat: [PHM-125] #comment - ALM 서버와 AMRS DB 동기화 - 24.04.02

---

src/main/java/com/arms/api/jira/jiraserver/controller/JiraServerController.java
src/main/java/com/arms/api/util/communicate/external/엔진통신기.java

- 리턴 타입 변경
- 잘못된 계정 정보로 요청시 오류 처리
클러스터2 : [DockerSwarm] …

:alien: feat: [RedMine#20] #comment 계정 검증 API 리턴 타입 변경 - 24.04.02

---

src/main/java/com/arms/api/jira/jiraserver/service/JiraServerImpl.java
src/main/java/com/arms/api/requirement/reqadd/service/ReqAddImpl.java
src/main/java/com/arms/api/requirement/reqstatus/controller/ReqStatusController.java

1. 서버 엔티티 동기화 메소드 미사용 코드 제거
2. sonarqube 기반 리팩토링
[DockerSwarm] …

🙈 refactor: [PHM-125] #comment - 미사용 코드 제거 - 24.04.04

---

src/main/java/com/arms/api/jira/jiraissuestatus/model/JiraIssueStatusDTO.java
src/main/java/com/arms/api/jira/jiraserver/service/JiraServerImpl.java
src/main/java/com/arms/api/requirement/reqstate_category/controller/ReqStateCategoryController.java
src/main/java/com/arms/api/requirement/reqstate_category/model/ReqStateCategoryDTO.java
src/main/java/com/arms/api/requirement/reqstate_category/model/ReqStateCategoryEntity.java
src/main/java/com/arms/api/requirement/reqstate_category/service/ReqStateCategory.java
src/main/java/com/arms/api/requirement/reqstate_category/service/ReqStateCategoryImpl.java
src/main/java/com/arms/api/requirement/reqstate_category_log/controller/ReqStateCategoryLogController.java
src/main/java/com/arms/api/requirement/reqstate_category_log/model/ReqStateCategoryLogDTO.java
src/main/java/com/arms/api/requirement/reqstate_category_log/model/ReqStateCategoryLogEntity.java
src/main/java/com/arms/api/requirement/reqstate_category_log/service/ReqStateCategoryLog.java
src/main/java/com/arms/api/requirement/reqstate_category_log/service/ReqStateCategoryLogImpl.java
src/main/java/com/arms/api/util/communicate/external/response/jira/지라이슈상태_데이터.java
src/main/resources/com/arms/db/V14__init_aRMS.sql

1. REQSTATE_CATEGORY 추가
2. T_ARMS_JIRAISSUESTATUS - c_issue_type_maping_id 컬럼 추가 -> 클라우드 지라 이슈 상태 - 이슈 유형 아이디와 매핑
3. T_ARMS_REQSTATE - c_state_category_mapping_id 컬럼 추가 -> 고객사 상태 - 암스 상태 카테고리 매핑
[CodeAnalysis] …

🙈 feat: [redmine-phm-84] #comment flyway version up  - 24.07.22

---

src/main/java/com/arms/api/jira/jiraissuestatus/model/JiraIssueStatusEntity.java
src/main/java/com/arms/api/requirement/reqstate/controller/ReqStateController.java
src/main/java/com/arms/api/requirement/reqstate/model/ReqStateDTO.java
src/main/java/com/arms/api/requirement/reqstate/model/ReqStateEntity.java
src/main/java/com/arms/egovframework/javaservice/treeframework/service/TreeServiceImpl.java

1. JIRAISSUESTATUS 컬럼명 수정
2. REQSTATE - REQSTATECATAGORY - 1:1 단방향 연계 추가
3. REQSTATE - c_state_category_mapping_id null 허용 -> 1:1 단방향 연계 추가로 필드명을 Entity명 적용
4. updateNode.do API - 단방향 연계 Set하여 추가
[CodeAnalysis] …

🙈 feat: [redmine-phm-84] #comment ReqState - ReqStateCategory 단방향 연계 추가 - 24.07.23

---

src/main/java/com/arms/api/jira/jiraproject/controller/JiraProjectController.java
src/main/java/com/arms/api/jira/jiraproject/service/JiraProject.java
src/main/java/com/arms/api/jira/jiraproject/service/JiraProjectImpl.java

1. 클라우드 지라 프로젝트별 이슈유형별 이슈상태 조회 API 추가
[DockerSwarm] …

🙈 feat: [redmine-phm-84] #comment 프로젝트 - 이슈유형 - 이슈상태 조회 API - 24.07.26

---

src/main/java/com/arms/api/analysis/common/service/CommonServiceImpl.java
src/main/java/com/arms/api/requirement/reqadd/controller/ReqAddController.java
src/main/java/com/arms/api/requirement/reqstate/controller/ReqStateController.java
src/main/java/com/arms/api/requirement/reqstate_category/controller/ReqStateCategoryController.java
src/main/java/com/arms/egovframework/javaservice/treeframework/service/TreeServiceImpl.java

1. 완료 상태 카테고리 API 추가
2. c_type - "folder" 하드코딩 TreeConstant.Branch_TYPE로 변경 …

🙈 feat: [redmine-phm-84] #comment 상태 카테고리 API 추가 - 24.07.30

---

src/main/java/com/arms/api/requirement/reqstate/controller/ReqStateController.java
src/main/java/com/arms/api/requirement/reqstate_category/controller/ReqStateCategoryController.java

1. 카테고리 매핑된 상태목록 조회 API 추가
2. 완료 상태 카테고리 API 경로 변경
[DockerSwarm] …

🙈 feat: [redmine-phm-84] #comment 카테고리 매핑된 상태목록 조회 API 추가 - 24.07.31

---

src/main/java/com/arms/api/requirement/reqstate/controller/ReqStateController.java

🙈 refactor: [redmine-phm-84] #comment 상태 조회 시 sorted 카테고리 아이디 기준 오름차순 - 24.08.03

---

src/main/java/com/arms/api/analysis/resource/service/ResourceServiceImpl.java
src/main/java/com/arms/api/product_service/pdservice/service/PdServiceImpl.java
src/main/java/com/arms/api/requirement/reqadd/controller/ReqAddController.java
src/main/java/com/arms/api/requirement/reqadd/service/ReqAdd.java
src/main/java/com/arms/api/requirement/reqadd/service/ReqAddImpl.java

1. updateDatabase.do 요구사항 상태 업데이트 트랜잭션 분리 처리
2. SonarQube NPE 대응
3. 연결관리 D3차트 레벨4 Node Jira 표시에서 ALM으로 변경
[Kubernetes] …

🙈 refactor: [redmine-phm-84] #comment 요구사항 상태 업데이트 리팩토링, SonarQube 이슈 해결 - 24.08.12

---

src/main/java/com/arms/api/requirement/reqstate/controller/ReqStateController.java

1. addStateNode.do 상태 생성 API(Category set)
[DockerSwarm] …

🙈 feat: [redmine-phm-84] #comment 요구사항 상태 API - 24.08.13

---

src/main/java/com/arms/api/requirement/reqadd_state_pure/service/ReqAddStatePureImpl.java
src/main/java/com/arms/api/requirement/reqstate/controller/ReqStateController.java
src/main/java/com/arms/api/requirement/reqstate/service/ReqState.java
src/main/java/com/arms/api/requirement/reqstate/service/ReqStateImpl.java

1. 완료상태 조회 리팩토링 -> 완료상태 yml 설정에서 문구 조회 방식에서 상태 카테고리 c_closed 컬럼 조회 방식으로 변경 …

🙈 refactor: [redmine-phm-84] #comment 완료상태 조회 리팩토링 - 24.08.17

---

src/main/java/com/arms/api/analysis/cost/service/CostServiceImpl.java
src/main/java/com/arms/api/requirement/reqstate/controller/ReqStateController.java
src/main/java/com/arms/config/ArmsDetailUrlConfig.java
src/main/resources/application.yml

1. 완료상태 조회 API 리팩토링
2. 비용분석 완료 상태 조회 부분 리팩토링
3. yml 내 상태 완료 키워드 부분 삭제 …

🙈 refactor: [redmine-phm-84] #comment 완료상태 조회 리팩토링 2차 - 24.08.18

---

src/main/java/com/arms/api/requirement/reqstate/controller/ReqStateController.java
src/main/java/com/arms/api/requirement/reqstate/service/ReqState.java
src/main/java/com/arms/api/requirement/reqstate/service/ReqStateImpl.java

🙈 feat: [redmine-phm-84] #comment 요구사항 상태 기본값 설정 API 추가 - 24.08.21

---

src/main/java/com/arms/api/requirement/reqadd/controller/ReqAddController.java
src/main/java/com/arms/api/requirement/reqadd/service/ReqAdd.java
src/main/java/com/arms/api/requirement/reqadd/service/ReqAddImpl.java
src/main/java/com/arms/api/requirement/reqstate/controller/ReqStateController.java
src/main/java/com/arms/api/requirement/reqstate/service/ReqStateImpl.java
src/main/java/com/arms/api/util/communicate/internal/InternalService.java
src/main/java/com/arms/config/RouteTableConfig.java

1. 요구사항 상태 삭제 후 전체 요구사항 상태 업데이트 호출 추가
2. 전체 제품에 대한 요구사항 상태 변경 로직 Async 처리
3. 요구사항 상태변경 API 추가 및 내부 통신기 추가
4. Sonarqube 대응 …

🙈 feat: [redmine-phm-84] #comment 상태 삭제 후 요구사항 상태 변경 API 추가 - 24.08.24

---

src/main/java/com/arms/api/requirement/reqstate/controller/ReqStateController.java

🙈 fix: [redmine-phm-84] #comment 상태 filter 조건 제거 - 24.08.24

---

src/main/java/com/arms/api/jira/jiraserver/service/JiraServerImpl.java
src/main/java/com/arms/api/util/communicate/external/response/jira/지라이슈상태_카테고리_데이터.java

1. 상태 카테고리 프리셋 기능 추가를 위한 클라우드 지라 이슈상태 카테고리 데이터 항목 추가
2. JiraServerImpl 사용하지 않는 코드 정리
3. 현재 프리셋 방법을 하드코딩 적용 But  테이블 정의, yml 정의 방법 중 진행 필요 1 대 N의 경우 상태가 랜덤으로 업데이트 되는 현상 발생할 예정이므로 변경 필요
[CodeAnalysis] …

🙈 feat: [redmine-phm-84] #comment 상태 카테고리 프리셋 기능 추가 - 24.08.29
